package com.model;

// Generated Jul 20, 2022 3:06:03 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Medical generated by hbm2java
 */
public class Medical implements java.io.Serializable {

	private Integer mid;
	private String name;
	private String address;
	private String process;
	private String distance;
	private String images;
	private String staphana;
	private String type;
	private Date date;

	public Medical() {
	}

	public Medical(String name, String address, String process, String distance, String images, String staphana,
			String type, Date date) {
		this.name = name;
		this.address = address;
		this.process = process;
		this.distance = distance;
		this.images = images;
		this.staphana = staphana;
		this.type = type;
		this.date = date;
	}

	public Integer getMid() {
		return this.mid;
	}

	public void setMid(Integer mid) {
		this.mid = mid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getProcess() {
		return this.process;
	}

	public void setProcess(String process) {
		this.process = process;
	}

	public String getDistance() {
		return this.distance;
	}

	public void setDistance(String distance) {
		this.distance = distance;
	}

	public String getImages() {
		return this.images;
	}

	public void setImages(String images) {
		this.images = images;
	}

	public String getStaphana() {
		return this.staphana;
	}

	public void setStaphana(String staphana) {
		this.staphana = staphana;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
