package com.model;

// Generated Jul 20, 2022 3:06:03 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Person generated by hbm2java
 */
public class Person implements java.io.Serializable {

	private Integer id;
	private String name;
	private String education;
	private String address;
	private String images;
	private String dob;
	private String work;
	private Date date;

	public Person() {
	}

	public Person(Date date) {
		this.date = date;
	}

	public Person(String name, String education, String address, String images, String dob, String work, Date date) {
		this.name = name;
		this.education = education;
		this.address = address;
		this.images = images;
		this.dob = dob;
		this.work = work;
		this.date = date;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEducation() {
		return this.education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getImages() {
		return this.images;
	}

	public void setImages(String images) {
		this.images = images;
	}

	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	public String getWork() {
		return this.work;
	}

	public void setWork(String work) {
		this.work = work;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
