package com.model;

// Generated Jul 20, 2022 3:06:03 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Query generated by hbm2java
 */
public class Query implements java.io.Serializable {

	private Integer id;
	private String name;
	private String email;
	private String subject;
	private String message;
	private Date qdate;

	public Query() {
	}

	public Query(String name, String email, String subject, String message, Date qdate) {
		this.name = name;
		this.email = email;
		this.subject = subject;
		this.message = message;
		this.qdate = qdate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Date getQdate() {
		return this.qdate;
	}

	public void setQdate(Date qdate) {
		this.qdate = qdate;
	}

}
