package com.model;

// Generated Jul 20, 2022 3:06:03 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * School generated by hbm2java
 */
public class School implements java.io.Serializable {

	private Integer sid;
	private String name;
	private String address;
	private String process;
	private String images;
	private String diwas;
	private String type;
	private Date date;

	public School() {
	}

	public School(String name, String address, String process, String images, String diwas, String type, Date date) {
		this.name = name;
		this.address = address;
		this.process = process;
		this.images = images;
		this.diwas = diwas;
		this.type = type;
		this.date = date;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getProcess() {
		return this.process;
	}

	public void setProcess(String process) {
		this.process = process;
	}

	public String getImages() {
		return this.images;
	}

	public void setImages(String images) {
		this.images = images;
	}

	public String getDiwas() {
		return this.diwas;
	}

	public void setDiwas(String diwas) {
		this.diwas = diwas;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
